/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zgs_gifit_utils_ImageUtil */

#ifndef _Included_com_zgs_gifit_utils_ImageUtil
#define _Included_com_zgs_gifit_utils_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zgs_gifit_utils_ImageUtil
 * Method:    decodeYUV420SP
 * Signature: ([BII)[I
 */
JNIEXPORT void JNICALL Java_com_zgs_gifu_utils_ImageUtil_decodeYUV420SP
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
